"""Readout writer: a one-page markdown result the team can paste into Notion/Slack."""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from .llm import LLM
from .models import Experiment, Funnel

log = logging.getLogger(__name__)

SYSTEM = """You write crisp experiment readouts for a growth team. Lead with the decision, then the number,
then what we learned and what to do next. No hype, no hedging beyond what the statistics support. Under 250 words."""


def mde_note(s) -> str:
    return "a 5% relative lift at 80% power"


def _template(exp: Experiment, funnel: Funnel) -> str:
    s, p = exp.stats, exp.proposal
    assert s
    verdict = {"ship": "SHIP", "kill": "KILL", "inconclusive": "INCONCLUSIVE"}.get(s.decision, s.decision.upper())
    sign = "+" if s.relative_lift >= 0 else ""
    lines = [
        f"# {p.name}: {verdict}",
        "",
        f"**Funnel:** {funnel.name} · **Step:** {p.target_step} · **Ran:** {s.days_running} days · **Flag:** `{exp.artifact.flag_key if exp.artifact else '-'}`",
        "",
        "## Result",
        f"- Treatment converted **{s.treatment.rate:.2%}** vs control **{s.control.rate:.2%}** → **{sign}{s.relative_lift:.1%} relative lift** "
        f"(95% CI {s.ci_low:+.1%} to {s.ci_high:+.1%}, {'p < 0.001' if s.p_value < 0.001 else f'p = {s.p_value:.3f}'}).",
        f"- Sample: {s.control.users:,} control / {s.treatment.users:,} treatment ({s.required_per_arm:,} per arm required for {s.power:.0%} observed power).",
        f"- Expected funnel impact: {sign}{(exp.ranking.expected_funnel_lift if exp.ranking else 0) * (s.relative_lift / p.expected_lift if p.expected_lift else 1):.1%} on overall conversion." if s.decision == "ship" else "",
        "",
        "## Hypothesis",
        p.hypothesis,
        "",
        "## What we changed",
        p.change,
        "",
        "## What we learned",
    ]
    if s.decision == "ship":
        lines.append(f"The hypothesis held. Predicted {p.expected_lift:+.0%}, observed {s.relative_lift:+.1%}: "
                     + ("close to the prior." if abs(s.relative_lift - p.expected_lift) < 0.05 else "the prior was off; recalibrate similar bets."))
        lines += ["", "## Next", f"- Roll `{exp.artifact.flag_key if exp.artifact else 'flag'}` to 100% and delete the control path.",
                  "- Watch downstream steps for a week to confirm the lift carries through.",
                  f"- Follow-up: push further on {p.category} at {p.target_step}."]
    elif s.decision == "kill":
        lines.append(f"The treatment hurt conversion ({s.relative_lift:+.1%}). The hypothesis that {p.hypothesis[:1].lower() + p.hypothesis[1:].rstrip('.')} did not hold for this audience.")
        lines += ["", "## Next", "- Roll back to control and archive the flag.", f"- Deprioritize {p.category} changes at {p.target_step} until we have qualitative data."]
    else:
        lines.append(f"No reliable effect after {s.days_running} days and {min(s.control.users, s.treatment.users):,} per arm "
                     f"({s.sample_fraction:.0%} of the sample needed for {mde_note(s)}). "
                     + (f"The raw p-value ({s.p_value:.3f}) did not clear the sequential threshold ({s.alpha_threshold:.4f}) at this sample size: "
                        "early looks need a stricter bar to avoid false positives. " if s.p_value < 0.05 else "")
                     + f"Any true lift is likely within {s.ci_low:+.0%} to {s.ci_high:+.0%}.")
        lines += ["", "## Next", "- Roll back to control.", "- If we still believe in it, rerun with a larger change or a bigger audience."]
    lines += ["", f"_Generated by Autopilot on {datetime.now(timezone.utc):%Y-%m-%d}._"]
    return "\n".join(l for l in lines if l is not None)


class ReadoutWriter:
    def __init__(self, llm: LLM):
        self.llm = llm

    def write(self, exp: Experiment, funnel: Funnel) -> str:
        base = _template(exp, funnel)
        if not self.llm.enabled:
            return base
        try:
            out = self.llm.text(SYSTEM, f"Rewrite this readout in your voice, keeping every number exactly:\n\n{base}")
            return out or base
        except Exception as exc:  # noqa: BLE001
            log.warning("LLM readout failed (%s); using template", exc)
            return base
